# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, pathsep-separated, to be prepended to sys.path in env.py.
# defaults to sys.path containing the current directory.
prepend_syspath = .

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max characters of slug to include in revision filename
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported from sys.path
# without installing them
# syspath_inject = true

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, paths must be separated by ';'
# version_locations = %(here)s/alembic/versions

# version_path_separator = ;

# set to 'true' to search for locations recursively
# recursive_version_locations = false

# the output encoding used when writing new migration files
# output_encoding = utf-8

# sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/ai_safety


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for details.


[logging]
default_handler = console


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
